### ISSUE TITLE
Error: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by patricieni** [rflamary/POT#40] opened 2018-01-30 20:52 UTC
Hello, 

I am trying to compute ot.emd2() distances between two histograms and for some reason, it fails with this error. I have managed to compute between other histograms so I am wondering what might be wrong with my criteria. 

They satisfy the constraint of sum =  1 - which is the only one i'm aware of? 

I can fix the problem using np.ascontiguousarray() but I'm trying to get an intuition if I'm doing something wrong to begin with. 

<img width="536" alt="screen shot 2018-01-30 at 21 44 30" src="https://user-images.githubusercontent.com/3986917/35590656-d1b39bc4-0607-11e8-9dd7-758ed02701ef.png">

**Comment by ncourty** [comment] 2018-01-30 21:05
Hello Patric,
Yes it seems there is a flow in the way you defined/constructed your histograms. To be sure about the problem, you might want to print r3.flags to verify it is not C_CONTIGUOUS. The way you fixed the problem is ok to me, but you can also do something like r3 = r3.copy(order='C'). Hope this helps !
Nicolas

**Comment by patricieni** [comment] 2018-01-30 21:09
Thanks Nicolas for the quick response and for the workaround! I appreciate it

Are there any other constraints the histogram should obey? I have positive values summing to 1, that should be it I guess..

**Comment by ncourty** [comment] 2018-01-30 21:15
Yes ! Positive values summing to one is the only constraint. If you have a lot of zeros in both r3 and r4 you can also consider accelerations by cleaning zeros (function clean_zeros in utils module). I will now close the issue.

**Closed by ncourty** 2018-01-30 21:15 UTC
